### ISSUE TITLE
wrong links for shutterstock and anilist

### ISSUE THREAD

**Issue by this-fifo** [matchai/resume#1]
Shutterstock link
https://github.com/matchai/resume/blob/master/src/index.html#L186

Anilist link
https://github.com/matchai/resume/blob/master/src/index.html#L333

Hey man, hope I am not being intrusive opening an issue on someone's personal resume (you're probably like `wtf` reading this 😂) but just wanted to point out some links that seem to be wrong as I randomly came across your page today

btw, I am a big fan of the starship prompt — _it's been my default prompt for quite a while now_ — and everything else you do, you're a great source of inspiration, wish you all the best!

**Comment by matchai** [comment]
Haha good catch!
Better for you to have caught it than a potential employer. 😜
